### ISSUE TITLE
SPIKE: As a developer, I want to learn TypeScript

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#20]
## Description:

- Everyone on the team should have a basic understanding of TypeScript.  What are the benefits of using TypeScript, etc.

- Everyone on the team understands the difference between Dynamically typed languages, and Statically typed languages

## Resources:

- [Exercism](https://exercism.org/tracks/typescript/exercises)
- [Google Classroom](https://classroom.google.com/w/NTE3MzUwMDg0NTY0/t/all)

### Resources for learning:

- [Handbook](https://www.typescriptlang.org/docs/handbook/intro.html)
- [Official Documentation](https://www.typescriptlang.org/docs/)
- [Codecademy](https://www.codecademy.com/learn/learn-typescript)
- [O'Reily](https://www.oreilly.com/library/view/typescript-cookbook/9781098136642/)
- [Direct Tutorials](https://www.typescripttutorial.net/)
- [Learn TypeScript](https://learntypescript.dev/)

## Tasks:

- [x] Everyone on the team needs TypeScript installed
- [x] The team should decide the appropriate time to get together and convert a previously done project in any other language and make it in TypeScript.
- [x] Decide on a single small-medium project as a team and separate to work on it individually and then discuss how everyone did it. 

## Definition of Done:
- [x] Every Success Criteria is met and reviewed by at least one other developer
- [x] Code is reviewed by at least one other developer
