### ISSUE TITLE
SPIKE: As a developer, I want to learn Angular

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#21]
## Description:
As a team, you will learn the basics of Angular applications by researching Angular and eventually following the Tour of Heroes guide

## Resources:

- [Tour of Heroes](https://angular.io/tutorial/tour-of-heroes)
- [Angular Docs](https://angular.io/docs)

## Tasks:

- [x] Each assigned team member has completed the Tour of Heroes
     - [x] Joshua
     - [x] Deep
     - [x] Noah

## Definition of Done:
- [x] Every Success Criteria is met and reviewed by at least one other developer
- [x] Code is reviewed by at least one other developer
- [x] Useful documentation
