### ISSUE TITLE
SPIKE: As a developer, I want to learn how to use Rest Assured

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#22]
## Description:
We need to learn how to write API-level unit tests using the Rest Assured testing framework. The main focus areas of study are below:

- Need to learn what dependencies need to be installed in order to use Rest Assured
- Need to learn what level of testing Rest Assured tests
- Need to learn how to mock services with Rest Assured
- Need to learn how to run Rest Assured unit tests
- Need to learn how to configure Rest Assured unit tests
### Different Ways to Mock
- Mockito
- MvcMock

## Resources:

- [Getting Started](https://github.com/rest-assured/rest-assured/wiki/GettingStarted)
- [Baeldung](https://www.baeldung.com/rest-assured-tutorial)
- [Video](https://youtu.be/oVNbaBlrhbo?si=syGLeilfwD3g-Vd0)

## Tasks:
- [x]  Write 3+ useful tests for the Spring Spike Assignment (Optional)
- [x] Team discusses resources and what we learned whenever everyone is ready

## Definition of Done:
- [x] Every Success Criteria is met and reviewed by at least one other developer
- [x] Code is reviewed by at least one other developer
- [x] All test cases are passing
- [x] Useful documentation
