### ISSUE TITLE
As a developer, we need to create our starter Angular Application

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#23]
## Description:
As a team, we need an Angular application that we can add features to for later stories. The application should be the bare minimum output of the Angular CLI create start app. The code for this should be hosted in the same repository as the Spring Boot application. The starter Angular application should be rendered from one of the Spring Boot endpoints.

## Resources:
- [Capstone Site Notes](https://sites.google.com/d/1zOopRR7qBmE1JCpgX4ghUgx-uPY-z2P2/p/1WuOCgIQvJPS-j2xPTffhPkABiNvW3Hw1/edit)

## Tasks:
- [x] Angular is installed
- [x] Angular app runs without errors
- [x] Code is pulled and merged to reports repo

## Definition of Done:
- [x] Every Success Criteria is met and reviewed by at least one other developer
- [x] Code is reviewed by at least one other developer
- [x] Useful documentation
