### ISSUE TITLE
SPIKE: As a team, we need to understand what insights the Product Owner wants to see

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#24]
## Description:
Meet with @chris-marfia on what types of insights you will want to see in our application. This might drive some changes when it comes to data that is needed. 

## Tasks:
- [x] Meet with @chris-marfia in a meeting
- [x] Document what analytics the product owner wants to see
- [x] Document which charts should be used for which analytics 
- [x] Document what data is needed for each chart.

## Definition of Done:
- [x] Every Success Criteria is met and reviewed by at least one other developer
- [x] Code is reviewed by at least one other developer
- [x] All test cases are passing
- [x] Useful documentation

**Comment by epricewillis** [comment]
Graphing chart of what succeeded and failed 

- Use chart.js, min-max chart or stacked bar chart

- Wants to see the number of success and failed

- success rate based on iterations. Group by ruleset. Find the mean iteration, then filter the passing iteration. For each ruleset group, what is the mean iteration. Use pie chart or polar chart

- Group by week. Ex: Last seven days

- Metric: Number of iterations it took to complete it

- Metric: Number of iterations user tried to complete it (what the user expected)

- Use financial chart on chart.js (for min,max,avg) https://www.chartjs.org/chartjs-chart-financial/

-Have one chart displaying at a time. Possibly a drop down or sidebar

- Bonus: to graph (scatter or bubble chart) (y axis=layouts, x-axis= number of iteration) every iteration. Based off the metric of how fast something has succeeded

**Comment by Dpppatel** [comment]
Chart size might change
Some graphing chart showing aggregation that represents the pass and failure percentage,

Metrics
How many successes happened on the same day (last 7 days) (Stacked bar or Bar graph)
Stacked bar chart (suggesstion)
Free to explore
Charts hould update upon the filters
Avg iterations it takes by the layout 
(Legends) Group by ruleSet -> find the mean of the iteration and filter by passing. Bar chart (Pie or Radar chart)
How many iterations it took to complete. (Stacked bar chart) 
Iteration = 1 move. 
Compare it with the limit of iterations allowed.

**Comment by chris-marfia** [comment]
Here are the metrics I am looking for.

1. Given the last seven days, can you provide me with daily averages for successful and failed simulations by RuleSets?
2. Given all successful simulations, can you provide me with a chart that will allow me to see the average iterations it takes to solve a specific layout?
3. Given all successful iterations, I would like to see the maximum planned iterations, minimum planned iterations, maximum completed iterations, and minimum completed iterations. 
> This is typically done using a candlestick chart: https://www.investopedia.com/trading/candlestick-charting-what-is-it/
