### ISSUE TITLE
SPIKE: As a Developer, we want to learn how to use Postman.

### ISSUE THREAD

**Issue by Dpppatel** [Access-Point-Program/cohort-3-reports#30]
## Description:
(A clear and concise description of what the issue is about.)
As a team, we need to understand more about Rest APIs and how to rest them. To do so we need to learn Postman. This is an application that will allow us to document, test, run, and examine Rest APIs.

## Resources:

- [x] https://www.postman.com/postman/workspace/30-days-of-postman-for-developers/overview

## Tasks:
(Include specific tasks in the order they need to be done in.)

- [x] Everyone on the team should have Postman installed for this story.
- [x] To learn this tool we should complete the first 12 days of the 30 days of postman challenge.
     - [x] Brian 
     - [x] Deep
     - [x] Elissa
     - [x] Myesha

## Definition of Done:
- [x] Every Success Criteria is met
- [x] Code is reviewed by at least one other developer
- [x] All test cases are passing
- [x] Useful documentation
