### ISSUE TITLE
SPIKE: As a Developer, We need to learn Python

### ISSUE THREAD

**Issue by Dpppatel** [Access-Point-Program/cohort-3-reports#31]
## Description:
(A clear and concise description of what the issue is about.)
Complete the Codeacademy course, then pick 3 medium projects to solve from the exercise website. 

## Resources

- [Exercism](https://exercism.org/tracks/python/exercises)
- [CodeAcademy](https://www.codecademy.com/enrolled/courses/learn-python-3)
- [Capstone Site](https://sites.google.com/d/1zOopRR7qBmE1JCpgX4ghUgx-uPY-z2P2/p/1YAxRkm6_uZA6Adv-LCMHkCEr1liOyxL5/edit)

## Tasks:
(Include specific tasks in the order they need to be done in.)

- [ ] The CodeAcademy course is complete
- [ ] At least 2 Medium exercises are completed from the Exercism website.
- [ ] Everything is Documented on the Capstone site

## Definition of Done:
- [ ] Every Success Criteria is met and reviewed by at least one other developer
- [ ] Code is reviewed by at least one other developer
- [ ] All test cases are passing
- [ ] Useful documentation
