### ISSUE TITLE
Build out Sidebar

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#36]
## Description:
We need to have a team agreement on if the current iteration of the sidebar is okay and push it to GitHub.

## Tasks:
- [x] Each member of the team agrees on the Sidebar's looks

## Definition of Done:
- [x] Every Success Criteria is met and reviewed by at least one other developer
- [x] Code is reviewed by at least one other developer
- [x] All test cases are passing
- [x] Useful documentation
