### ISSUE TITLE
As a developer, I need to build out the Filters form in Angular

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#37]
## Description:
Currently, we don't have the data that we to populate the form.  We will be creating the form in our Angular application to match the design of our UI. The form should have the event handler wired up. However, they will not have any functionality yet. 

## Screenshots:

![Image](https://github.com/Access-Point-Program/cohort-3-reports/assets/141256275/ddbf343d-182a-4900-bdd4-5bd1ae88a2b7)

## Tasks:
(Include specific tasks in the order they need to be done.)

- [x] We need a service for getting the data(Rulesets and layouts) from a mock API.
- [x] We need a fake API. 
- [x] We need a section to the right side of the screen, with both filters in it.
- [x] Apply Correct (Using Angular Components) Styles to match the cohesiveness of the page.
- [ ] Add working event handlers for each filter form.

## Acceptance Criteria 

- [x] The filters UI is created within our Angular Application. 
- [ ] The code is pushed to main GitHub branch. 

## Definition of Done:
- [ ] Every Success Criteria is met and reviewed by at least one other developer
- [ ] Code is reviewed by at least one other developer
- [ ] All test cases are passing
- [ ] Useful documentation
