### ISSUE TITLE
As a developer, I need to build out the reports Table

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#38]
## Description:
Currently, we don't have the data that we to populate the reports table. We will need to implement the table within our Angular application. The table should match the mockup that was provided by the instructor. 

## Screenshots:

![Image](https://github.com/Access-Point-Program/cohort-3-reports/assets/141256275/296dccc9-dd00-475a-b8fa-aed0f72f3574)

## Resources 

 [Angular powered BootStrap](https://ng-bootstrap.github.io/#/components/accordion/overview)

## Tasks:
(Include specific tasks in the order they need to be done.)

- [x] We need a service for getting the data.
- [x] Talk with Hocus Pocus and take the endpoint(s).
- [x] We need a section in the middle of the screen, with Tables in it.
- [x] We need to implement Pagination
- [x] Apply Correct (Using Angular Components) Styles to match the cohesiveness of the page.

## Acceptance Criteria 

- [x] The filters UI is created within our Angular Application. 
- [x] Code is Pushed on the main branch on GitHub.

## Definition of Done:
- [x] Every Success Criteria is met and reviewed by at least one other developer
- [x] Code is reviewed by at least one other developer
- [x] All test cases are passing
- [x] Useful documentation
